// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXkiT1ZNdBlKFEfEfV3HiPCe-dLSSVQmM',
    appId: '1:1095894111356:web:5575a1d58504b75acd65f9',
    messagingSenderId: '1095894111356',
    projectId: 'messageboardapp-e938b',
    authDomain: 'messageboardapp-e938b.firebaseapp.com',
    storageBucket: 'messageboardapp-e938b.firebasestorage.app',
    measurementId: 'G-VJPJ1E0LZ6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmeOlI6UXv6R33pqjgUXqQdbVqbQf5x_w',
    appId: '1:1095894111356:android:bcea6ed2f6f6e6f6cd65f9',
    messagingSenderId: '1095894111356',
    projectId: 'messageboardapp-e938b',
    storageBucket: 'messageboardapp-e938b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtSdbD1OCHJ0hVFk4nIiJWSeUE-rC4WVE',
    appId: '1:1095894111356:ios:70393c3375136299cd65f9',
    messagingSenderId: '1095894111356',
    projectId: 'messageboardapp-e938b',
    storageBucket: 'messageboardapp-e938b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtSdbD1OCHJ0hVFk4nIiJWSeUE-rC4WVE',
    appId: '1:1095894111356:ios:70393c3375136299cd65f9',
    messagingSenderId: '1095894111356',
    projectId: 'messageboardapp-e938b',
    storageBucket: 'messageboardapp-e938b.firebasestorage.app',
    iosBundleId: 'com.example.demo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBXkiT1ZNdBlKFEfEfV3HiPCe-dLSSVQmM',
    appId: '1:1095894111356:web:973ced1fde3ab334cd65f9',
    messagingSenderId: '1095894111356',
    projectId: 'messageboardapp-e938b',
    authDomain: 'messageboardapp-e938b.firebaseapp.com',
    storageBucket: 'messageboardapp-e938b.firebasestorage.app',
    measurementId: 'G-HJSHGT5DBF',
  );

}